-- Generated by mockwave schemaToSql for app "kitdemo". Apply on the app's own stack; do not edit by hand.
create schema if not exists "kitdemo";
grant usage on schema "kitdemo" to authenticated;

create table "kitdemo"."food" (
  id uuid primary key,
  "ownerId" uuid not null default auth.uid(),
  "createdAt" timestamptz not null,
  "updatedAt" timestamptz not null,
  "deletedAt" timestamptz,
  "name" text not null,
  "kcal" double precision not null,
  unique (id, "ownerId")
);
create index on "kitdemo"."food" ("ownerId");
alter table "kitdemo"."food" enable row level security;
create policy own_rows on "kitdemo"."food" for all to authenticated
  using ("ownerId" = auth.uid()) with check ("ownerId" = auth.uid());
grant select, insert, update, delete on "kitdemo"."food" to authenticated;

create table "kitdemo"."meal" (
  id uuid primary key,
  "ownerId" uuid not null default auth.uid(),
  "createdAt" timestamptz not null,
  "updatedAt" timestamptz not null,
  "deletedAt" timestamptz,
  "food" uuid not null,
  foreign key ("food", "ownerId") references "kitdemo"."food" (id, "ownerId"),
  "kind" text not null check ("kind" in ('breakfast', 'lunch', 'dinner')),
  "eatenAt" timestamptz not null,
  "note" text,
  unique (id, "ownerId")
);
create index on "kitdemo"."meal" ("ownerId");
alter table "kitdemo"."meal" enable row level security;
create policy own_rows on "kitdemo"."meal" for all to authenticated
  using ("ownerId" = auth.uid()) with check ("ownerId" = auth.uid());
grant select, insert, update, delete on "kitdemo"."meal" to authenticated;

create table "kitdemo"."goal" (
  id uuid primary key,
  "ownerId" uuid not null default auth.uid(),
  "createdAt" timestamptz not null,
  "updatedAt" timestamptz not null,
  "deletedAt" timestamptz,
  "kcal" double precision not null,
  "active" boolean not null,
  unique (id, "ownerId")
);
create index on "kitdemo"."goal" ("ownerId");
alter table "kitdemo"."goal" enable row level security;
create policy own_rows on "kitdemo"."goal" for all to authenticated
  using ("ownerId" = auth.uid()) with check ("ownerId" = auth.uid());
grant select, insert, update, delete on "kitdemo"."goal" to authenticated;
