/**
 * Kit schema to SQL for a per-app stack (W2 template, citadel docs/refactor/w2-confederation-plan.md).
 * One Postgres schema per app, one table per entity, owner-scoped row-level security. The app
 * stack has no GoTrue: `auth.uid()` reads the platform-signed JWT, and there is no foreign key to
 * `auth.users`. The output is a migration for Jeff to apply; nothing here runs it.
 */

import { validateSchema, type FieldDef, type KitSchema } from './schema';

const SLUG = /^[a-z][a-z0-9_]*$/;
const q = (name: string) => `"${name}"`;
const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;

function column(app: string, f: FieldDef): string {
  const type = { string: 'text', number: 'double precision', boolean: 'boolean', date: 'timestamptz', enum: 'text', ref: 'uuid' }[f.type];
  let sql = `${q(f.name)} ${type}${f.optional ? '' : ' not null'}`;
  if (f.type === 'enum') sql += ` check (${q(f.name)} in (${f.enum!.map(lit).join(', ')}))`;
  // Composite key: a row may only point at a row with the same owner, so a ref cannot probe another user's ids.
  if (f.type === 'ref') sql += `,\n  foreign key (${q(f.name)}, "ownerId") references ${app}.${q(f.to!)} (id, "ownerId")`;
  return sql;
}

/** Returns the migration SQL that creates the app's schema, tables, grants and owner policies. */
export function schemaToSql(app: string, schema: KitSchema): string {
  if (!SLUG.test(app)) throw new Error(`schemaToSql: app slug "${app}" must match ${SLUG}`);
  const problems = validateSchema(schema, { signedIn: true });
  if (problems.length) throw new Error(`schemaToSql: invalid schema: ${problems.join('; ')}`);
  const household = schema.entities.filter((e) => e.scope === 'household').map((e) => e.name);
  if (household.length) throw new Error(`schemaToSql: household scope is not supported yet (${household.join(', ')})`);

  const out = [
    `-- Generated by mockwave schemaToSql for app "${app}". Apply on the app's own stack; do not edit by hand.`,
    `create schema if not exists ${app};`,
    `grant usage on schema ${app} to authenticated;`,
  ];
  for (const e of schema.entities) {
    const t = `${app}.${q(e.name)}`;
    const cols = [
      `id uuid primary key`,
      `"ownerId" uuid not null default auth.uid()`,
      `"createdAt" timestamptz not null`,
      `"updatedAt" timestamptz not null`,
      `"deletedAt" timestamptz`,
      ...e.fields.map((f) => column(app, f)),
      `unique (id, "ownerId")`,
    ];
    out.push(
      '',
      `create table ${t} (\n  ${cols.join(',\n  ')}\n);`,
      `create index on ${t} ("ownerId");`,
      `alter table ${t} enable row level security;`,
      `create policy own_rows on ${t} for all to authenticated\n  using ("ownerId" = auth.uid()) with check ("ownerId" = auth.uid());`,
      `grant select, insert, update, delete on ${t} to authenticated;`,
    );
  }
  return out.join('\n') + '\n';
}
