/**
 * Mockwave - Data Mocking Wave
 * 
 * The third app in the Waves Suite (Rackwave: audio, Fluxwave: UI, Mockwave: data).
 * Pattern: copy-as-code for generating realistic mock data structures.
 * 
 * User flow:
 * 1. Paste or import your real data schema/source
 * 2. Configure mocking rules (field types, distributions, relationships)
 * 3. Generate mock data
 * 4. Copy the generated mock code to use in your tests/development
 */

import { useState } from 'react';

// Placeholder favicon - will be replaced with actual SVG
import './index.css';

export default function App() {
  const [schemaInput, setSchemaInput] = useState<string>('');
  const [mockOutput, setMockOutput] = useState<string>('');
  const [error, setError] = useState<string | null>(null);

  const handleGenerateMock = () => {
    setError(null);
    if (!schemaInput.trim()) {
      setError('Please enter a schema or paste your data source');
      return;
    }
    
    // TODO: Implement deterministic parser for data schemas
    // For now, just echo back with a mockwave placeholder
    const mock = generateMockFromSchema(schemaInput);
    setMockOutput(mock);
  };

  return (
    <div className="mockwave-app">
      <header className="mockwave-header">
        <h1>Mockwave</h1>
        <p className="tagline">Generate realistic mock data with copy-as-code</p>
      </header>

      <main className="mockwave-main">
        <section className="import-panel">
          <h2>Import Your Schema</h2>
          <p>
            Paste your data schema, TypeScript interface, or JSON structure below.
            Mockwave will generate realistic mock data that matches your structure.
          </p>
          
          <textarea
            value={schemaInput}
            onChange={(e) => setSchemaInput(e.target.value)}
            placeholder={`Paste your schema here, e.g.:

// TypeScript interface
interface User {
  id: string;
  name: string;
  email: string;
  age: number;
  isActive: boolean;
  createdAt: Date;
}

// Or JSON Schema
{
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "name": { "type": "string" }
  }
}`}
            rows={12}
          />
          
          {error && <div className="error">{error}</div>}
          
          <button 
            className="primary-btn" 
            onClick={handleGenerateMock}
            disabled={!schemaInput.trim()}
          >
            Generate Mock Data
          </button>
        </section>

        {mockOutput && (
          <section className="export-panel">
            <h2>Generated Mock</h2>
            <div className="tabs">
              <button className="tab active">Code</button>
              <button className="tab">Diff</button>
            </div>
            <pre className="code-output">{mockOutput}</pre>
            <div className="copy-actions">
              <button className="btn" onClick={() => navigator.clipboard.writeText(mockOutput)}>
                Copy Mock Code
              </button>
              <button className="btn" onClick={() => navigator.clipboard.writeText(mockOutput)}>
                Copy Diff
              </button>
            </div>
          </section>
        )}
      </main>

      <footer className="mockwave-footer">
        <p>The Waves Suite: Data Mocking for Modern Development</p>
      </footer>
    </div>
  );
}

// TODO: Replace with deterministic parser (like Rackwave's parseWebAudioSnippet)
// This is a placeholder that will be replaced with the actual implementation
function generateMockFromSchema(schema: string): string {
  // Simple heuristic: if it looks like TypeScript, generate TypeScript mock
  if (schema.includes('interface') || schema.includes('type ')) {
    return `// Auto-generated mock data from your schema
// Mockwave - deterministic mock generation

${generateTypeScriptMock(schema)}`;
  }
  // If it looks like JSON, generate JSON mock
  if (schema.trim().startsWith('{') || schema.trim().startsWith('[')) {
    return generateJSONMock(schema);
  }
  // Default: wrap in a basic mock structure
  return `// Mockwave generated mock
// TODO: Implement based on your schema
{
  id: 'mock-' + Math.random().toString(36).substring(2, 9),
  name: 'Mock Item',
  value: 42,
  isActive: true,
  createdAt: new Date().toISOString(),
}`;
}

function generateTypeScriptMock(schema: string): string {
  // Extract interface name for better output
  const interfaceMatch = schema.match(/interface\s+(\w+)/);
  const typeName = interfaceMatch ? interfaceMatch[1] : 'Mock';
  
  return `export const mock${typeName}: ${typeName} = {
  id: crypto.randomUUID(),
  name: 'Mock ${typeName}',
  description: 'Generated by Mockwave',
  // ... other fields will be populated based on your schema
};

export const mock${typeName}List: ${typeName}[] = Array(10).fill(null).map(() => mock${typeName});`;
}

function generateJSONMock(schema: string): string {
  return `{
  "mockData": {
    "generatedAt": "${new Date().toISOString()}",
    "sourceSchema": "Your schema here",
    "items": [
      { "id": 1, "name": "Mock Item 1", "value": 42 },
      { "id": 2, "name": "Mock Item 2", "value": 84 },
      { "id": 3, "name": "Mock Item 3", "value": 126 }
    ]
  }
}`;
}
